stages:
  - test

test-internal-link:
  stage: test
  image: node:12
  before_script:
    - yarn install
  script:
   - yarn lint-md --quiet

test-build:
  stage: test
  image: node:12
  before_script:
    - yarn install
  script:
   - yarn docs:build

test-external-link:
  stage: test
  image: node:12
  before_script:
    - yarn install
  script:
   - yarn extended-lint-md --quiet
  allow_failure: true
