[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "16"
[build]
  command = "yarn docs:build"
  publish = ".vuepress/dist/"
[context.deploy-preview.environment]
  NODE_VERSION = "16"
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ["*"]
  template = "hierarchical"
  pathPrefix = "documentation-snds.health-data-hub.fr"