const tables_sidebar = require('./tables_sidebar');

const sidebar = [
    {
        title: 'Introduction',
        path: '/introduction/',
        children: [
            '/introduction/snds',
        ]
    },
    {
        title: 'Fiches thématiques',
        path: '/fiches/',
        children: [
            '/fiches/historique_donnees',
            '/fiches/cmu_c',
            '/fiches/audioprotheses',
            '/fiches/beneficiaires_ald',
            '/fiches/optique',
            ['/fiches/cartographie_pathologies', 'Cartographie des pathologies'],
            '/fiches/glossaire',
            '/fiches/graph_reperage_sniiram',
        ]
    },
    {
        title: 'Ressources',
        path: '/ressources/',
        children: [
            '/ressources/',
            '/ressources/meetup',
            ['/ressources/kwikly', 'KWIKLY'],
            '/ressources/portail_sniiram',
            '/ressources/programmes',
            '/ressources/bibliographie',
        ]
    },
    {
        title: "Concepts",
        path: "/concepts/",
        children: [
            "/concepts/accident_du_travail",
            "/concepts/acte",
            "/concepts/affections_de_longue_duree",
            "/concepts/aide_medicalisee_d_etat",
            "/concepts/assure",
            "/concepts/autorisation_de_mise_sur_le_marche",
            "/concepts/ayant_droit",
            "/concepts/base_de_remboursement",
            "/concepts/beneficiaire",
            "/concepts/caisse_de_rattachement_du_professionnel_de_sante",
            "/concepts/caisse_statistique_du_professionnel_de_sante",
            "/concepts/categorie_d_etablissement",
            "/concepts/clinique_prive",
            "/concepts/code_de_la_classification_anatomique_therapeutique_et_chimique_atc",
            "/concepts/code_identifiant_de_presentation",
            "/concepts/codes_unite_communes_de_dispensation",
            "/concepts/codification_sniiram_de_la_prestation",
            "/concepts/coefficient",
            "/concepts/complement_ou_majoration_d_actes",
            "/concepts/consommant",
            "/concepts/couverture_maladie_universelle_complementaire",
            "/concepts/couverture_maladie_universelle_de_base",
            "/concepts/date_d_execution_ou_date_de_soins",
            "/concepts/date_d_hospitalisation",
            "/concepts/date_de_prescription",
            "/concepts/date_de_remboursement",
            "/concepts/date_de_traitement",
            "/concepts/etablissement",
            "/concepts/etablissement_prive",
            "/concepts/etablissement_public",
            "/concepts/etablissement_public_ou_psph",
            "/concepts/etablissements_de_sante",
            "/concepts/etablissements_et_structures",
            "/concepts/etablissements_medico_sociaux",
            "/concepts/forfait_journalier",
            "/concepts/honoraires",
            "/concepts/identifiant_anonyme_du_beneficiaire",
            "/concepts/incapacite_permanente",
            "/concepts/indemnites_journalieres",
            "/concepts/invalidite",
            "/concepts/liste_des_produits_et_prestations",
            "/concepts/maladie_professionnelle",
            "/concepts/medecin_traitant",
            "/concepts/medecine_de_ville",
            "/concepts/medicament",
            "/concepts/mode_d_exercice_du_professionnel_de_sante",
            "/concepts/montant_de_la_depense",
            "/concepts/montant_du_depassement",
            "/concepts/montant_rembourse",
            "/concepts/nature_d_assurance",
            "/concepts/non_consommant",
            "/concepts/numero_finess_geographique",
            "/concepts/numero_finess_juridique",
            "/concepts/organisme",
            "/concepts/organisme_d_affiliation_du_beneficiaire",
            "/concepts/organisme_d_assurance_complementaire",
            "/concepts/organisme_de_liquidation_de_la_prestation",
            "/concepts/parcours_de_soins",
            "/concepts/patientele",
            "/concepts/population_protegee",
            "/concepts/prescription",
            "/concepts/prestataire_de_soins",
            "/concepts/prestation",
            "/concepts/prestation_de_reference",
            "/concepts/prestation_en_especes",
            "/concepts/prestation_en_nature",
            "/concepts/produits_de_sante",
            "/concepts/professionnel_de_sante",
            "/concepts/professionnel_de_sante_executant",
            "/concepts/professionnel_de_sante_prescripteur",
            "/concepts/professionnel_medical",
            "/concepts/professionnel_paramedical",
            "/concepts/quantite_associee_a_des_actes_ou_a_des_prestations",
            "/concepts/regime_alsace_moselle",
            "/concepts/regime_obligatoire",
            "/concepts/regimes_speciaux",
            "/concepts/reste_a_charge_assure",
            "/concepts/sections_locales_mutualistes",
            "/concepts/specialite_medicale",
            "/concepts/statut_juridique_de_l_etablissement",
            "/concepts/structures_hors_etablissements",
            "/concepts/taux_de_remboursement",
            "/concepts/ticket_moderateur",
            "/concepts/tiers_payant",
            "/concepts/type_d_enveloppe",
            "/concepts/type_de_remboursement",
            "/concepts/type_de_saisie_de_la_feuille_de_soin"
        ]
    },
    {
        title: 'Tables',
        children: tables_sidebar
    },
    {
        title: 'Contribuer',
        path: '/contribuer/',
        children: [
            '/contribuer/',
            '/contribuer/introduction_gitlab',
            '/contribuer/tutoriel_markdown',
            '/contribuer/developpement_local',
            '/contribuer/nouveau_fichier',
        ]
    }
];

module.exports = {
    title: 'Documentation du SNDS',
    description: "Projet collaboratif pour documenter et faciliter l'utilisation du SNDS",
    themeConfig: {
        repo: 'http://gitlab.com/healthdatahub/documentation-snds',
        docsDir: '.',
        editLinks: true,
        editLinkText: 'Éditer sur GitLab',
        nav: [
            {text: 'Forum entraide', link: 'https://entraide.health-data-hub.fr/'},
            {text: 'Dico interactif', link: 'http://dico-snds.health-data-hub.fr/'},
        ],
        sidebar: sidebar,
        sidebarDepth: 1,
        lastUpdated: 'Dernière mise à jour',
	algolia: {
	  apiKey: 'b1d88a4e2413821b4ebe7441ecc95a97',
	  indexName: 'health-data-hub-snds'
	}
    }
}
